(function(){
  const C={navy:'1B365D',dark:'0E2438',teal:'2A9D8F',blue:'2D5F7A',gold:'E0A64B',red:'C84C4C',grey:'5A6675',line:'DDE7F0',light:'F7FAFD'};
  const months=['January','February','March','April','May','June'];
  function fmt(n){return Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0});}
  function pct(n){return (Number(n||0)*100).toFixed(1)+'%';}
  function cleanSku(s){s=String(s||''); if(s.includes('Hi Dee'))return'Hi Dee Drops'; if(s.includes('300'))return'Dinixir 300'; if(s.includes('40 ml'))return'Dinixir 40 ml'; if(s.includes('80 ml'))return'Dinixir 80 ml'; if(s.includes('OLAXY')&&s.includes('20'))return'Olaxy 20'; if(s.includes('OLAXY')&&s.includes('40'))return'Olaxy 40'; if(s.includes('Unicast 4'))return'Unicast 4'; if(s.includes('Unicast 5'))return'Unicast 5'; return s.slice(0,30);}
  function dataRows(){const E=window.S1_DATA||{d:{},r:[]},D=E.d||{};return (E.r||[]).map(x=>({year:x[0],month:(D.month||[])[x[1]],rep:(D.rep||[])[x[2]],area:(D.area||[])[x[3]],brand:(D.brand||[])[x[4]],sku:(D.sku||[])[x[5]],sales:x[6]||0}));}
  function unique(rows,key){return [...new Set(rows.map(r=>r[key]).filter(Boolean))];}
  function addTitle(s,title,sub){s.addText(title,{x:.45,y:.28,w:12.1,h:.35,fontSize:22,bold:true,color:C.dark,margin:0}); if(sub)s.addText(sub,{x:.47,y:.75,w:12,h:.25,fontSize:9.5,color:C.grey,margin:0});}
  function card(s,x,y,w,h,label,value,sub,color){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.06,fill:{color:'FFFFFF'},line:{color:C.line}});s.addShape(pptx.ShapeType.rect,{x,y,w:.06,h,fill:{color:color||C.teal},line:{color:color||C.teal}});s.addText(label,{x:x+.16,y:y+.12,w:w-.25,h:.18,fontSize:7.5,bold:true,color:C.grey,margin:0});s.addText(value,{x:x+.16,y:y+.42,w:w-.25,h:.34,fontSize:17,bold:true,color:C.dark,margin:0,fit:'shrink'});if(sub)s.addText(sub,{x:x+.16,y:y+.84,w:w-.25,h:.16,fontSize:6.6,color:C.grey,margin:0,fit:'shrink'});}
  function note(s,x,y,w,h,t,accent){s.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.04,fill:{color:'FFFFFF'},line:{color:C.line}});s.addShape(pptx.ShapeType.rect,{x:x+.05,y:y+.08,w:.06,h:h-.16,fill:{color:accent||C.teal},line:{color:accent||C.teal}});s.addText(t,{x:x+.18,y:y+.12,w:w-.3,h:h-.2,fontSize:9.2,color:C.dark,margin:0,fit:'shrink'});}
  function tbl(s,x,y,w,h,heads,rows,fs){let arr=[heads].concat(rows);s.addTable(arr,{x,y,w,h,fontSize:fs||6.5,border:{type:'solid',color:'D9E3EC',pt:.45},margin:.035,fill:'FFFFFF',fit:'shrink',valign:'mid',rowH:.25});s.addShape(pptx.ShapeType.rect,{x,y,w,h:.27,fill:{color:C.navy},line:{color:C.navy}});let cw=w/heads.length;heads.forEach((hd,i)=>s.addText(hd,{x:x+i*cw+.03,y:y+.06,w:cw-.06,h:.14,fontSize:6.5,bold:true,color:'FFFFFF',margin:0,fit:'shrink'}));}
  function addMasterFooter(s){s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:.08,fill:{color:C.navy},line:{color:C.navy}});s.addText('S1 Business Review | CEO Presentation',{x:.45,y:7.16,w:5,h:.12,fontSize:6,color:'7B8794',margin:0});s.addText('MS Pharma',{x:11.5,y:7.16,w:1.3,h:.12,fontSize:6,color:'7B8794',align:'right',margin:0});}
  function addSlide(ppt,title,sub){let s=ppt.addSlide();s.background={color:C.light};addMasterFooter(s);addTitle(s,title,sub);return s;}
  function topRows(arr,n,by){return [...arr].sort((a,b)=>(b[by]||0)-(a[by]||0)).slice(0,n);}
  async function buildPpt(){
    try{
      var P=window.PptxGenJS||window.pptxgenjs||window.pptxgen; if(!P){alert('PowerPoint library is still loading. Try again in a few seconds.');return;}
      const rows=dataRows(),T=window.S1_TARGETS; if(!rows.length||!T){alert('Dashboard data is still loading. Press Ctrl+F5 and try again.');return;}
      window.pptx=new P(); pptx.layout='LAYOUT_WIDE'; pptx.author='MS Pharma'; pptx.subject='S1 CEO Business Review'; pptx.title='S1 CEO Business Review Reconciled'; pptx.company='MS Pharma'; pptx.lang='en-US';
      const total25=rows.filter(r=>r.year===2025).reduce((a,b)=>a+b.sales,0), total26=T.overall.sales, target=T.overall.target, growth=total26/total25-1;
      const reps=T.reps.map(r=>({rep:r.name,s25:rows.filter(x=>x.year===2025&&x.rep===r.name).reduce((a,b)=>a+b.sales,0),s26:r.sales,target:r.target,ach:r.ach,gap:r.sales-r.target,change:r.sales-rows.filter(x=>x.year===2025&&x.rep===r.name).reduce((a,b)=>a+b.sales,0)}));
      const brands=T.brands.map(b=>({brand:b.name,s25:rows.filter(x=>x.year===2025&&x.brand===b.name).reduce((a,c)=>a+c.sales,0),s26:b.sales,target:b.target,ach:b.ach,gap:b.sales-b.target,change:b.sales-rows.filter(x=>x.year===2025&&x.brand===b.name).reduce((a,c)=>a+c.sales,0)}));
      const brandNames=brands.map(b=>b.brand), repNames=reps.map(r=>r.rep);
      let s=pptx.addSlide();s.background={color:C.light};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:4.1,h:7.5,fill:{color:C.navy},line:{color:C.navy}});s.addText('S1 2026\nBusiness Review',{x:.55,y:1.0,w:3.1,h:1.2,fontSize:27,bold:true,color:'FFFFFF',fit:'shrink'});s.addText('CEO Presentation\nReconciled official achievement',{x:.55,y:5.85,w:3.1,h:.55,fontSize:13,color:'DDE7F0'});s.addText('S1 Sales Performance Dashboard',{x:4.55,y:1.2,w:7.9,h:.55,fontSize:29,bold:true,color:C.dark,margin:0});s.addText('All dashboard sections included: Overview, Performance Detail, Area & Channels, Targets & Achievement, Methodology.',{x:4.57,y:1.92,w:7.9,h:.42,fontSize:12,color:C.grey,margin:0});card(s,4.65,3.05,1.8,1.05,'2025 Restated',fmt(total25)+' JOD','Like-for-like',C.blue);card(s,6.75,3.05,1.8,1.05,'2026 Sales',fmt(total26)+' JOD','Official report',C.teal);card(s,8.85,3.05,1.8,1.05,'Achievement',pct(T.overall.ach),'vs target',C.gold);card(s,10.95,3.05,1.8,1.05,'Growth',pct(growth),'vs restated 2025',C.teal);
      s=addSlide(pptx,'Executive summary','Strong growth with a clear target recovery agenda.');card(s,.6,1.2,2.3,1.0,'S1 2026 Sales',fmt(total26)+' JOD','Official rep report',C.teal);card(s,3.05,1.2,2.3,1.0,'Target',fmt(target)+' JOD','S1 target',C.navy);card(s,5.5,1.2,2.3,1.0,'Achievement',pct(T.overall.ach),'Gap '+fmt(total26-target)+' JOD',C.gold);card(s,7.95,1.2,2.3,1.0,'Growth',pct(growth),'+ '+fmt(total26-total25)+' JOD',C.teal);card(s,10.4,1.2,2.3,1.0,'Brand Control',pct(T.overall.officialBrandAch),'Private only',C.blue);note(s,.7,2.65,3.8,1.1,'Growth is materially positive: +'+fmt(total26-total25)+' JOD vs the restated 2025 base.',C.teal);note(s,4.75,2.65,3.8,1.1,'Achievement remains below target. The recovery gap is '+fmt(target-total26)+' JOD.',C.gold);note(s,8.8,2.65,3.8,1.1,'Hi Dee is above target. Olaxy and Unicast are the largest brand gaps.',C.red);note(s,.7,4.1,3.8,1.1,'Yazeed is above target; Mahmoud is close; other reps require account-level recovery plans.',C.teal);note(s,4.75,4.1,3.8,1.1,'Hospitals and Subagent contribution accounts are growing and need disciplined coverage.',C.blue);note(s,8.8,4.1,3.8,1.1,'Mohammad Al-Omari corrected to official: '+fmt(T.reps.find(r=>r.name.includes('محمد')).sales)+' JOD / '+pct(T.reps.find(r=>r.name.includes('محمد')).ach)+'.',C.gold);
      s=addSlide(pptx,'Methodology and official controls','2025 restated on 2026 structure; 2026 reconciled to official reports.');tbl(s,.75,1.35,11.8,1.5,['Step','Control','Definition'],[['1','Restate 2025','Apply 2026 account/area/Medical Rep structure to 2025 sales.'],['2','Contribution %','Split every contribution account by each rep percentage in both years.'],['3','Official 2026','Reconcile Medical Rep × SKU to official Private with subagents report.'],['4','Target validation','Use official targets by rep and brand to calculate achievement.']],7.6);card(s,.9,3.45,2.4,.95,'Rep official total',fmt(T.overall.sales)+' JOD',pct(T.overall.ach),C.teal);card(s,3.55,3.45,2.4,.95,'Brand official total',fmt(T.overall.officialBrandSales)+' JOD',pct(T.overall.officialBrandAch),C.blue);card(s,6.2,3.45,2.4,.95,'Official variance',fmt(T.overall.officialBrandSales-T.overall.sales)+' JOD','Private only vs with subagents',C.gold);card(s,8.85,3.45,2.4,.95,'Restated 2025',fmt(total25)+' JOD','Comparable base',C.navy);note(s,1.0,5.0,10.8,.75,'The two official reports are retained as separate controls. Rep evaluation uses the rep report; brand evaluation uses the brand report.',C.gold);
      s=addSlide(pptx,'Medical Rep achievement vs target','Official S1 2026 sales and targets by Medical Rep.');s.addChart(pptx.ChartType.bar,[{name:'Sales',labels:repNames,values:reps.map(r=>r.s26)},{name:'Target',labels:repNames,values:reps.map(r=>r.target)}],{x:.65,y:1.25,w:6.7,h:4.8,showLegend:true,legendPos:'b',catAxisLabelFontSize:7,valAxisLabelFontSize:7,chartColors:[C.teal,C.navy]});tbl(s,7.65,1.25,5.05,2.0,['Rep','Sales','Target','Ach.','Gap'],reps.map(r=>[r.rep,fmt(r.s26),fmt(r.target),pct(r.ach),fmt(r.gap)]),6.5);note(s,7.75,3.65,4.75,1.0,'Only Yazeed is above target. Rep-level recovery must be managed weekly by top accounts and SKU gap.',C.red);
      s=addSlide(pptx,'Brand achievement vs target','Official brand control shows where the target gap is concentrated.');s.addChart(pptx.ChartType.bar,[{name:'Sales',labels:brandNames,values:brands.map(b=>b.s26)},{name:'Target',labels:brandNames,values:brands.map(b=>b.target)}],{x:.65,y:1.25,w:6.7,h:4.8,showLegend:true,legendPos:'b',catAxisLabelFontSize:9,valAxisLabelFontSize:7,chartColors:[C.teal,C.navy]});tbl(s,7.65,1.25,5.05,1.75,['Brand','Sales','Target','Ach.','Gap'],brands.map(b=>[b.brand,fmt(b.s26),fmt(b.target),pct(b.ach),fmt(b.gap)]),6.5);note(s,7.75,3.35,4.75,.85,'Hi Dee is above target. Olaxy and Unicast are the priority gaps; Dinixir is close but still below target.',C.gold);
      s=addSlide(pptx,'Medical Rep growth: like-for-like view','2025 restated vs 2026 official-reconciled.');const repCh=[...reps].sort((a,b)=>b.change-a.change);s.addChart(pptx.ChartType.bar,[{name:'Growth JOD',labels:repCh.map(r=>r.rep),values:repCh.map(r=>r.change)}],{x:.65,y:1.25,w:6.8,h:4.7,showLegend:false,catAxisLabelFontSize:7,valAxisLabelFontSize:7,chartColors:[C.teal]});tbl(s,7.65,1.25,5.05,2.0,['Rep','2025','2026','Change','Growth'],repCh.map(r=>[r.rep,fmt(r.s25),fmt(r.s26),fmt(r.change),pct(r.change/r.s25)]),6.4);note(s,7.75,3.7,4.75,.85,'Yazeed has the largest growth contribution; Mahmoud has strong sales but lower growth rate.',C.teal);
      let sku=[];unique(rows,'sku').forEach(k=>{const s25=rows.filter(r=>r.year===2025&&r.sku===k).reduce((a,b)=>a+b.sales,0),s26=rows.filter(r=>r.year===2026&&r.sku===k).reduce((a,b)=>a+b.sales,0);sku.push({sku:k,brand:(rows.find(r=>r.sku===k)||{}).brand,s25,s26,change:s26-s25,growth:s25?s26/s25-1:null});});
      s=addSlide(pptx,'SKU performance detail','SKU-level growth and target performance.');s.addChart(pptx.ChartType.bar,[{name:'Change JOD',labels:sku.map(x=>cleanSku(x.sku)),values:sku.map(x=>x.change)}],{x:.65,y:1.25,w:6.8,h:4.7,showLegend:false,catAxisLabelFontSize:7,valAxisLabelFontSize:7,chartColors:[C.gold]});tbl(s,7.65,1.25,5.05,2.55,['Brand','SKU','2025','2026','Growth'],sku.map(x=>[x.brand,cleanSku(x.sku),fmt(x.s25),fmt(x.s26),x.growth==null?'—':pct(x.growth)]),5.6);note(s,7.75,4.25,4.75,.8,'Dinixir 40 ml and Hi Dee drive strong growth; Unicast 5 is the only SKU with negative YoY growth.',C.red);
      const ch=unique(rows,'rep').map(rep=>{const f=(yr,areaLike)=>rows.filter(r=>r.rep===rep&&r.year===yr&&(!areaLike||r.area==='Hospitals')).reduce((a,b)=>a+b.sales,0);return{rep,h25:f(2025,'Hospitals'),h26:f(2026,'Hospitals'),s25:rows.filter(r=>r.rep===rep&&r.year===2025&&r.area!=='Hospitals').reduce((a,b)=>a+b.sales,0),s26:rows.filter(r=>r.rep===rep&&r.year===2026&&r.area!=='Hospitals').reduce((a,b)=>a+b.sales,0)}});
      s=addSlide(pptx,'Area & Channels','Hospitals and account-contribution territories by Medical Rep.');s.addChart(pptx.ChartType.bar,[{name:'2025 Hospitals',labels:ch.map(c=>c.rep),values:ch.map(c=>c.h25)},{name:'2026 Hospitals',labels:ch.map(c=>c.rep),values:ch.map(c=>c.h26)}],{x:.65,y:1.25,w:5.8,h:2.25,showLegend:true,legendPos:'b',catAxisLabelFontSize:6,valAxisLabelFontSize:6,chartColors:[C.blue,C.teal]});s.addChart(pptx.ChartType.bar,[{name:'2025 Other Areas',labels:ch.map(c=>c.rep),values:ch.map(c=>c.s25)},{name:'2026 Other Areas',labels:ch.map(c=>c.rep),values:ch.map(c=>c.s26)}],{x:6.75,y:1.25,w:5.8,h:2.25,showLegend:true,legendPos:'b',catAxisLabelFontSize:6,valAxisLabelFontSize:6,chartColors:[C.blue,C.teal]});tbl(s,.75,4.15,11.75,1.5,['Rep','Hosp 2025','Hosp 2026','Hosp Growth','Other 2025','Other 2026','Other Growth'],ch.map(c=>[c.rep,fmt(c.h25),fmt(c.h26),pct(c.h26/c.h25-1),fmt(c.s25),fmt(c.s26),pct(c.s26/c.s25-1)]),5.8);
      const area=[];unique(rows,'area').forEach(a=>{const s25=rows.filter(r=>r.year===2025&&r.area===a).reduce((x,y)=>x+y.sales,0),s26=rows.filter(r=>r.year===2026&&r.area===a).reduce((x,y)=>x+y.sales,0);area.push({area:a,s25,s26,change:s26-s25,growth:s25?s26/s25-1:null});});const topA=topRows(area,12,'s26');
      s=addSlide(pptx,'Top areas','Area sales performance from the dashboard.');s.addChart(pptx.ChartType.bar,[{name:'2025',labels:topA.map(a=>a.area),values:topA.map(a=>a.s25)},{name:'2026',labels:topA.map(a=>a.area),values:topA.map(a=>a.s26)}],{x:.65,y:1.25,w:7.0,h:4.9,showLegend:true,legendPos:'b',catAxisLabelFontSize:5.5,valAxisLabelFontSize:6,chartColors:[C.blue,C.teal]});tbl(s,7.9,1.25,4.75,3.0,['Area','2026','Change','Growth'],topA.slice(0,10).map(a=>[a.area,fmt(a.s26),fmt(a.change),a.growth==null?'—':pct(a.growth)]),5.7);
      const monthly=months.map(m=>({m,s25:rows.filter(r=>r.year===2025&&r.month===m).reduce((a,b)=>a+b.sales,0),s26:rows.filter(r=>r.year===2026&&r.month===m).reduce((a,b)=>a+b.sales,0)}));
      s=addSlide(pptx,'Monthly trend','S1 run-rate by month.');s.addChart(pptx.ChartType.line,[{name:'2025 Restated',labels:monthly.map(m=>m.m.slice(0,3)),values:monthly.map(m=>m.s25)},{name:'2026',labels:monthly.map(m=>m.m.slice(0,3)),values:monthly.map(m=>m.s26)}],{x:.65,y:1.25,w:8.2,h:4.7,showLegend:true,legendPos:'b',catAxisLabelFontSize:8,valAxisLabelFontSize:7,chartColors:[C.blue,C.teal]});tbl(s,9.2,1.35,3.3,2.2,['Month','2025','2026','Change'],monthly.map(m=>[m.m.slice(0,3),fmt(m.s25),fmt(m.s26),fmt(m.s26-m.s25)]),6.4);note(s,9.2,4.0,3.3,.85,'Use weekly run-rate to close the remaining target gap before full-year review.',C.gold);
      const mo=T.reps.find(r=>r.name.includes('محمد'));s=addSlide(pptx,'Mohammad Al-Omari reconciliation','Corrected to official report values.');card(s,.65,1.25,2.3,1.0,'Original model',fmt(mo.originalCalcSales)+' JOD','Before correction',C.blue);card(s,3.15,1.25,2.3,1.0,'Official sales',fmt(mo.sales)+' JOD','Final KPI',C.teal);card(s,5.65,1.25,2.3,1.0,'Correction',fmt(mo.sales-mo.originalCalcSales)+' JOD','Across SKUs',C.gold);card(s,8.15,1.25,2.3,1.0,'Target',fmt(mo.target)+' JOD','Official target',C.navy);card(s,10.65,1.25,2.3,1.0,'Achievement',pct(mo.ach),'Final KPI',C.teal);note(s,.8,3.0,11.8,1.2,'The gap was not an achievement formula error. It came from reconstructed 2026 account/subagent allocation being below the official “Private with subagents” report across multiple SKUs, especially Hi Dee. Final KPI is '+fmt(mo.sales)+' JOD / '+pct(mo.ach)+'.',C.red);
      s=addSlide(pptx,'CEO-level action plan','Move from growth to target recovery execution.');tbl(s,.65,1.35,12.0,2.1,['#','Priority','Issue','Action','KPI'],[['1','Protect Hi Dee','Above target','Secure availability and maintain high-value accounts','Forecast accuracy'],['2','Recover Olaxy','Largest brand gap','Rep × account recovery plan for 20s and 40s','Weekly gap closure'],['3','Recover Unicast','Under target; Unicast 5 decline','Focus on key accounts and refill demand','SKU growth'],['4','Dinixir closeout','Close remaining target gap','Convert high-growth 40 ml and 300 caps opportunities','Account conversion'],['5','Rep coaching','Uneven target achievement','Weekly rep review by account and SKU','Run-rate']],7.0);note(s,.9,4.3,3.6,.95,'Start: weekly target gap review by rep, brand, SKU and account.',C.teal);note(s,4.9,4.3,3.6,.95,'Stop: reporting growth without target-gap accountability.',C.red);note(s,8.9,4.3,3.6,.95,'Continue: protect Hi Dee and high-growth channels.',C.blue);
      s=addSlide(pptx,'ROTT business review frame','Role · Objective · Type · Tone.');tbl(s,1.1,1.5,11.2,2.1,['ROTT','CEO-ready presentation frame'],[['Role','First-Line Sales Manager presenting a reconciled, data-backed S1 review.'],['Objective','Explain performance, target gaps, growth drivers, risks and recovery actions.'],['Type','Professional business review with editable charts and data appendices.'],['Tone','Analytical, concise, accountable and action-oriented.']],9.0);note(s,1.1,4.5,11.2,.9,'Closing message: “We delivered strong like-for-like growth, validated achievement to official reports, and now need disciplined execution to close the target gap — mainly Olaxy, Unicast and selected rep-level gaps.”',C.gold);
      s=addSlide(pptx,'Appendix — Rep × Brand matrix','All brands by rep from dashboard data.');let rb=[];repNames.forEach(r=>brandNames.forEach(b=>{const s25=rows.filter(x=>x.year===2025&&x.rep===r&&x.brand===b).reduce((a,c)=>a+c.sales,0),s26=rows.filter(x=>x.year===2026&&x.rep===r&&x.brand===b).reduce((a,c)=>a+c.sales,0);rb.push([r,b,fmt(s25),fmt(s26),fmt(s26-s25),s25?pct(s26/s25-1):'—']);}));tbl(s,.55,1.2,12.25,4.8,['Rep','Brand','2025','2026','Change','Growth'],rb,5.8);
      const ra=[];repNames.forEach(r=>unique(rows.filter(x=>x.rep===r),'area').forEach(a=>{const s25=rows.filter(x=>x.year===2025&&x.rep===r&&x.area===a).reduce((z,c)=>z+c.sales,0),s26=rows.filter(x=>x.year===2026&&x.rep===r&&x.area===a).reduce((z,c)=>z+c.sales,0); if(s25||s26)ra.push({rep:r,area:a,s25,s26,change:s26-s25,growth:s25?s26/s25-1:null});}));ra.sort((a,b)=>b.s26-a.s26);for(let i=0;i<Math.min(72,ra.length);i+=18){s=addSlide(pptx,'Appendix — Rep × Area detail '+(i/18+1),'Top area rows from the dashboard by 2026 sales.');tbl(s,.55,1.2,12.25,4.8,['Rep','Area','2025','2026','Change','Growth'],ra.slice(i,i+18).map(a=>[a.rep,a.area,fmt(a.s25),fmt(a.s26),fmt(a.change),a.growth==null?'—':pct(a.growth)]),5.6);}
      await pptx.writeFile({fileName:'S1_CEO_Business_Review_Professional_Editable.pptx'});
    }catch(e){console.error('CEO PowerPoint export failed',e);alert('PowerPoint export failed: '+(e&&e.message?e.message:e));}
  }
  function ensureButton(){var actions=document.querySelector('.actions')||document.querySelector('.top')||document.body;if(!actions)return;var old=document.getElementById('downloadPpt');if(old)old.remove();var b=document.createElement('button');b.id='downloadPpt';b.className='btn';b.textContent='Download CEO PowerPoint';b.style.marginLeft='8px';b.addEventListener('click',buildPpt);actions.appendChild(b);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureButton);else ensureButton();
})();