(function(){
const E=window.S1_DATA||{d:{},r:[]};const D=E.d;const data=E.r.map(x=>({year:x[0],month:D.month[x[1]],rep:D.rep[x[2]],area:D.area[x[3]],brand:D.brand[x[4]],sku:D.sku[x[5]],sales:x[6]}));
const months=['January','February','March','April','May','June'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0}); const pct=n=>(100*n).toFixed(1)+'%';
const colors=['#2d5f7a','#2a9d8f','#e09f3e','#7b6ea8','#6b8e23','#b56576'];
const state={year:'compare',rep:'All',brand:'All',sku:'All',area:'All',month:'All'};
function uniq(key){return [...new Set(data.map(d=>d[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)));}
function populate(id,key,label){const s=$(id);s.innerHTML='<option value="All">All '+label+'</option>'+uniq(key).map(v=>`<option>${v}</option>`).join('');}
populate('#rep','rep','Medical Reps');populate('#brand','brand','Brands');populate('#sku','sku','SKUs');populate('#area','area','Areas');$('#month').innerHTML='<option value="All">All Months</option>'+months.map(x=>`<option>${x}</option>`).join('');
function filtered(){return data.filter(d=>(state.year==='compare'||String(d.year)===state.year)&&(state.rep==='All'||d.rep===state.rep)&&(state.brand==='All'||d.brand===state.brand)&&(state.sku==='All'||d.sku===state.sku)&&(state.area==='All'||d.area===state.area)&&(state.month==='All'||d.month===state.month));}
function group(rows,key,year){const m={};rows.filter(r=>!year||r.year===year).forEach(r=>m[r[key]]=(m[r[key]]||0)+r.sales);return m;}
function totals(rows){return [2025,2026].map(y=>rows.filter(r=>r.year===y).reduce((a,b)=>a+b.sales,0));}
function barSvg(labels,s1,s2){const w=760,row=34,left=180,right=25,top=20,h=top+labels.length*row+35,max=Math.max(1,...s1.map(Math.abs),...s2.map(Math.abs));let out=`<svg class="svgchart" viewBox="0 0 ${w} ${h}">`;labels.forEach((l,i)=>{let y=top+i*row;let a=Math.max(0,(s1[i]/max)*(w-left-right)),b=Math.max(0,(s2[i]/max)*(w-left-right));out+=`<text x="${left-8}" y="${y+17}" text-anchor="end" font-size="11" fill="#52606d">${String(l).slice(0,28)}</text><rect x="${left}" y="${y+2}" width="${a}" height="12" rx="2" fill="${colors[0]}"><title>2025: ${fmt(s1[i])}</title></rect><rect x="${left}" y="${y+17}" width="${b}" height="12" rx="2" fill="${colors[1]}"><title>2026: ${fmt(s2[i])}</title></rect>`});out+=`</svg><div class="legend"><span><i class="dot" style="background:${colors[0]}"></i>2025 restated</span><span><i class="dot" style="background:${colors[1]}"></i>2026</span></div>`;return out;}
function growth(a,b){return a?b/a-1:null;}
function renderChannels(rows){const channel=window.S1_CHANNEL||[];const visible=channel.filter(x=>state.rep==='All'||x.rep===state.rep);const reps=visible.map(x=>x.rep);$('#hospitalChart').innerHTML=barSvg(reps,visible.map(x=>x.hosp25),visible.map(x=>x.hosp26));$('#subagentChart').innerHTML=barSvg(reps,visible.map(x=>x.sub25),visible.map(x=>x.sub26));$('#channelTable').innerHTML='<thead><tr><th>Medical Rep</th><th>Hospitals 2025</th><th>Hospitals 2026</th><th>Hospitals Change</th><th>Hospitals Growth</th><th>Subagent 2025</th><th>Subagent 2026</th><th>Subagent Change</th><th>Subagent Growth</th></tr></thead><tbody>'+visible.map(x=>{let hd=x.hosp26-x.hosp25,hg=growth(x.hosp25,x.hosp26),sd=x.sub26-x.sub25,sg=growth(x.sub25,x.sub26);return `<tr><td>${x.rep}</td><td>${fmt(x.hosp25)}</td><td>${fmt(x.hosp26)}</td><td class="${hd>=0?'pos':'neg'}">${fmt(hd)}</td><td class="${hg>=0?'pos':'neg'}">${hg==null?'—':pct(hg)}</td><td>${fmt(x.sub25)}</td><td>${fmt(x.sub26)}</td><td class="${sd>=0?'pos':'neg'}">${fmt(sd)}</td><td class="${sg>=0?'pos':'neg'}">${sg==null?'—':pct(sg)}</td></tr>`}).join('')+'</tbody>';const map={};rows.forEach(r=>{let k=r.rep+'|'+r.area;map[k]=map[k]||{rep:r.rep,area:r.area,a:0,b:0};map[k][r.year===2025?'a':'b']+=r.sales;});let arr=Object.values(map).filter(x=>Math.abs(x.a)>0.0001||Math.abs(x.b)>0.0001).sort((x,y)=>x.rep.localeCompare(y.rep)||y.b-x.b);const totals26={};rows.filter(r=>r.year===2026).forEach(r=>totals26[r.rep]=(totals26[r.rep]||0)+r.sales);$('#repAreaTable').innerHTML='<thead><tr><th>Medical Rep</th><th>Area</th><th>2025 Restated</th><th>2026</th><th>Change</th><th>Growth</th><th>2026 Share of Rep</th></tr></thead><tbody>'+arr.map(x=>{let d=x.b-x.a,g=growth(x.a,x.b),share=totals26[x.rep]?x.b/totals26[x.rep]:null;return `<tr><td>${x.rep}</td><td>${x.area}</td><td>${fmt(x.a)}</td><td>${fmt(x.b)}</td><td class="${d>=0?'pos':'neg'}">${fmt(d)}</td><td class="${g>=0?'pos':'neg'}">${g==null?'—':pct(g)}</td><td>${share==null?'—':pct(share)}</td></tr>`}).join('')+'</tbody>';let top=[...arr].sort((x,y)=>Math.max(y.a,y.b)-Math.max(x.a,x.b)).slice(0,15);$('#repAreaChart').innerHTML=barSvg(top.map(x=>(state.rep==='All'?x.rep+' · ':'')+x.area),top.map(x=>x.a),top.map(x=>x.b));}
function render(){const rows=filtered(),[a,b]=totals(rows),g=a?b/a-1:null;$('#kpis').innerHTML=`<div class="kpi"><span>S1 2025 RESTATED</span><strong>${fmt(a)} JOD</strong><em>2026 contribution structure</em></div><div class="kpi"><span>S1 2026 SALES</span><strong>${fmt(b)} JOD</strong><em>same contribution basis</em></div><div class="kpi"><span>CHANGE</span><strong class="${b-a>=0?'pos':'neg'}">${fmt(b-a)} JOD</strong><em>2026 vs 2025</em></div><div class="kpi"><span>GROWTH</span><strong class="${g>=0?'pos':'neg'}">${g==null?'—':pct(g)}</strong><em>like-for-like</em></div>`;const reps=uniq('rep'),r25=group(rows,'rep',2025),r26=group(rows,'rep',2026);$('#repChart').innerHTML=barSvg(reps,reps.map(x=>r25[x]||0),reps.map(x=>r26[x]||0));const brands=uniq('brand'),b25=group(rows,'brand',2025),b26=group(rows,'brand',2026);$('#brandChart').innerHTML=barSvg(brands,brands.map(x=>b25[x]||0),brands.map(x=>b26[x]||0));const m25=group(rows,'month',2025),m26=group(rows,'month',2026);$('#monthChart').innerHTML=barSvg(months,months.map(x=>m25[x]||0),months.map(x=>m26[x]||0));const a26=group(rows,'area',2026),areas=Object.keys(a26).sort((x,y)=>(a26[y]||0)-(a26[x]||0)).slice(0,15),a25=group(rows,'area',2025);$('#areaChart').innerHTML=barSvg(areas,areas.map(x=>a25[x]||0),areas.map(x=>a26[x]||0));renderTable(rows);renderInsights(a,b,r25,r26,b25,b26);renderChannels(rows);}
function renderTable(rows){const map={};rows.forEach(r=>{const k=[r.rep,r.brand,r.sku].join('|');map[k]=map[k]||{rep:r.rep,brand:r.brand,sku:r.sku,a:0,b:0};map[k][r.year===2025?'a':'b']+=r.sales});const arr=Object.values(map).sort((x,y)=>y.b-x.b);$('#perfTable').innerHTML='<thead><tr><th>Medical Rep</th><th>Brand</th><th>SKU</th><th>2025 Restated</th><th>2026</th><th>Change</th><th>Growth</th></tr></thead><tbody>'+arr.map(x=>{let d=x.b-x.a,g=x.a?d/x.a:null;return `<tr><td>${x.rep}</td><td>${x.brand}</td><td>${x.sku}</td><td>${fmt(x.a)}</td><td>${fmt(x.b)}</td><td class="${d>=0?'pos':'neg'}">${fmt(d)}</td><td class="${g>=0?'pos':'neg'}">${g==null?'—':pct(g)}</td></tr>`}).join('')+'</tbody>';}
function renderInsights(a,b,r25,r26,b25,b26){let reps=Object.keys(r26).map(r=>[r,(r26[r]||0)-(r25[r]||0)]).sort((x,y)=>y[1]-x[1]);let brands=Object.keys(b26).map(r=>[r,(b26[r]||0)-(b25[r]||0)]).sort((x,y)=>y[1]-x[1]);$('#insights').innerHTML=`<div class="insight"><b>Overall</b><p>${a?pct(b/a-1)+' growth':'No comparable base'} vs restated 2025.</p></div><div class="insight"><b>Top rep growth contribution</b><p>${reps[0]?reps[0][0]+' · +'+fmt(reps[0][1])+' JOD':'—'}</p></div><div class="insight"><b>Top brand growth contribution</b><p>${brands[0]?brands[0][0]+' · +'+fmt(brands[0][1])+' JOD':'—'}</p></div>`;}
$$('select').forEach(s=>s.addEventListener('change',()=>{state[s.id]=s.value;render()}));$('#reset').addEventListener('click',()=>{Object.assign(state,{year:'compare',rep:'All',brand:'All',sku:'All',area:'All',month:'All'});$$('select').forEach(s=>s.selectedIndex=0);render()});$$('.nav button').forEach(b=>b.addEventListener('click',()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view).classList.add('active')}));$('#csv').addEventListener('click',()=>{let rows=filtered();let h=['year','month','rep','area','brand','sku','sales'];let csv=h.join(',')+'\n'+rows.map(r=>h.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='S1_filtered_data.csv';a.click()});render();
})();